version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - echo pre-build
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - ls -al